app/models.py
from app import db
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine


Base = declarative_base()
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/hydrodatahub', echo=True)


class region(db.Model):
    __tablename__ = 'region'
    __table_args__ = {'extend_existing': True}
    id_region = db.Column('id_region', db.Integer, primary_key=True)
    nom_region = db.Column('nom_region', db.String)
    value = db.Column('value', db.REAL)

    def __repr__(self):
        return '<date {}>'.format(self.value)


class station(db.Model):
    __tablename__ = 'station'
    __table_args__ = {'extend_existing': True}
    id_station = db.Column('id_station', db.Integer, primary_key=True)
    numero_station = db.Column('numero_station', db.String)
    province = db.Column('province', db.String)
    latitude = db.Column('latitude', db.REAL)
    longitude = db.Column('longitude', db.REAL)
    id_region = db.Column('id_region', db.Integer, db.ForeignKey(region.id_region))

    def __repr__(self):
        return '<amenagement {}>'.format(self.nom_amenagement)


class bassin(db.Model):
    __tablename__ = 'bassin'
    __table_args__ = {'extend_existing': True}
    id_bassin = db.Column('id_bassin', db.Integer, primary_key=True)
    numero_station = db.Column('numero_station', db.String, unique=True)
    nom_station = db.Column('nom_station', db.String)
    nom_equiv = db.Column('nom_equivalent', db.String)
    province = db.Column('province', db.String)
    regime = db.Column('regularisation', db.String)
    superficie = db.Column('superficie', db.Integer)
    latitude = db.Column('latitude', db.REAL)
    longitude = db.Column('longitude', db.REAL)
    id_region = db.Column('id_region', db.Integer, db.ForeignKey(region.id_region))

    def __repr__(self):
        return '<basins {}>'.format(self.id_bassin)


class amenagement(db.Model):
    __tablename__ = 'amenagement'
    __table_args__ = {'extend_existing': True}
    id_amenagement = db.Column('id_amenagement', db.Integer, primary_key=True)
    nom_amenagement = db.Column('nom_amenagement', db.String)
    id_bassin = db.Column('id_bassins', db.Integer, db.ForeignKey(bassin.id_bassin))

    def __repr__(self):
        return '<amenagement {}>'.format(self.nom_amenagement)


class reservoir(db.Model):
    __tablename__ = 'reservoir'
    __table_args__ = {'extend_existing': True}
    id_reservoir = db.Column('id_reservoir', db.Integer, primary_key=True)
    nom_amenagement = db.Column('nom_amenagement', db.String)
    id_bassin = db.Column('id_bassin', db.Integer, db.ForeignKey(bassin.id_bassin))
    id_amenagement = db.Column('id_amenagement', db.Integer, db.ForeignKey(amenagement.id_amenagement))

    def __repr__(self):
        return '<reservoirs {}>'.format(self.id_reservoir)


class evacuateur(db.Model):
    __tablename__ = 'evacuateur'
    __table_args__ = {'extend_existing': True}
    id_evacuateur = db.Column('id_evacuateur', db.Integer, primary_key=True)
    nom_amenagement = db.Column('nom_evacuateur', db.String)
    id_reservoir = db.Column('id_reservoir', db.Integer, db.ForeignKey(reservoir.id_reservoir))
    id_amenagement = db.Column('id_amenagement', db.Integer, db.ForeignKey(amenagement.id_amenagement))

    def __repr__(self):
        return '<evacuateur {}>'.format(self.id_evacuateur)


class centrale(db.Model):
    __tablename__ = 'centrale'
    __table_args__ = {'extend_existing': True}
    id_centrale = db.Column('id_centrale', db.Integer, primary_key=True)
    nom_centrale = db.Column('nom_centrale', db.String)
    id_reservoir = db.Column('id_reservoir', db.Integer, db.ForeignKey(reservoir.id_reservoir))
    id_amenagement = db.Column('id_amenagement', db.Integer, db.ForeignKey(amenagement.id_amenagement))

    def __repr__(self):
        return '<centrale {}>'.format(self.id_centrale)


class meta_series(db.Model):
    __tablename__ = 'meta_series'
    __table_args__ = {'extend_existing': True}
    id = db.Column('id', db.Integer, primary_key=True, unique=True)
    id_bassin = db.Column('id_bassin', db.Integer, db.ForeignKey(bassin.id_bassin))
    type_serie = db.Column('type_serie', db.String)
    pas_de_temps = db.Column('pas_de_temps', db.String)
    aggregation = db.Column('aggregation', db.String)
    unites = db.Column('unites', db.String)
    date_debut = db.Column('date_debut', db.DateTime(timezone=True))
    date_fin = db.Column('date_fin', db.DateTime(timezone=True))
    source = db.Column('source', db.String)

    def __repr__(self):
        return '<meta_ts {}>'.format(self.id)


class don_series(db.Model):
    __tablename__ = 'don_series'
    __table_args__ = {'extend_existing': True}
    id = db.Column('id', db.Integer, db.ForeignKey(meta_series.id), primary_key=True)
    date = db.Column('date', db.DateTime(timezone=True), primary_key=True)
    value = db.Column('value', db.REAL)

    def __repr__(self):
        return '<date {}>'.format(self.value)


Base.metadata.create_all(engine)

app/__init__.py
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask import Flask, request, current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from redis import Redis
import rq
from config import Config
from app.dashboards import Dash_App1, Dash_App2
import atexit
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from app.tasks.cehq import main as cehq_task

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # sched = BackgroundScheduler(daemon=True,
    #                             jobstores={'default': SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')})
    # # Explicitly kick off the background thread
    # sched.add_job(cehq_task, 'interval', hours=24)
    # sched.start()
    # # Shutdown your cron thread if the web process is stopped
    # atexit.register(lambda: sched.shutdown(wait=False))

    db.init_app(app)
    MIGRATION_DIR = os.path.join('migrations')
    migrate.init_app(app, db, directory=MIGRATION_DIR)
    # app.redis = Redis.from_url(app.config['REDIS_URL'])
    # app.task_queue = rq.Queue('microblog-tasks', connection=app.redis)
    #
    # from app.api import bp as api_bp
    # app.register_blueprint(api_bp, url_prefix='/api')

    # from app.dashboards import bp as dash_bp
    # app.register_blueprint(dash_bp, url_prefix='/dashboards')
    #
    # app = Dash_App1.Add_Dash(app)
    # app = Dash_App2.Add_Dash(app)

    if not app.debug and not app.testing:
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/hydrodatahub.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('hydro-datahub startup')

    return app


from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import query

app/dashboards/__init__.py
from flask import Blueprint

bp = Blueprint('dashboards',
               __name__,
               url_prefix='/dashboards',
               )

from app.dashboards import routes

app/dashboards/routes.py
from flask import render_template
# from flask_login import login_required
from . import bp
from . import Dash_App1, Dash_App2

@bp.route('/app1')
# @login_required
def app1_template():
    return render_template('dashboards/app1.html', dash_url=Dash_App1.url_base)

@bp.route('/app2')
# @login_required
def app2_template():
    return render_template('dashboards/app2.html', dash_url=Dash_App2.url_base)

app/templates/_post.html
    <table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('main.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(70) }}" />
                </a>
            </td>
            <td>
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', username=post.author.username) }}">
                            {{ post.author.username }}
                        </a>
                    </span>
                {% endset %}
                {{ _('%(username)s said %(when)s',
                    username=user_link, when=moment(post.timestamp).fromNow()) }}
                <br>
                <span id="post{{ post.id }}">{{ post.body }}</span>
                {% if post.language and post.language != g.locale %}
                <br><br>
                <span id="translation{{ post.id }}">
                    <a href="javascript:translate(
                                '#post{{ post.id }}',
                                '#translation{{ post.id }}',
                                '{{ post.language }}',
                                '{{ g.locale }}');">{{ _('Translate') }}</a>
                </span>
                {% endif %}
            </td>
        </tr>
    </table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.route_default') }}">Hydro Datahub</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('dashboards.app1_template') }}">{{ _('App1') }}</a></li>
                    <li><a href="{{ url_for('dashboards.app2_template') }}">{{ _('App2') }}</a></li>
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
                    {% else %}
                    <li>
                        <a href="{{ url_for('main.messages') }}">{{ _('Messages') }}
                            {% set new_messages = current_user.new_messages() %}
                            <span id="message_count" class="badge"
                                  style="visibility: {% if new_messages %}visible
                                                     {% else %}hidden{% endif %};">
                                {{ new_messages }}
                            </span>
                        </a>
                    </li>
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('Profile') }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% if current_user.is_authenticated %}
        {% with tasks = current_user.get_tasks_in_progress() %}
        {% if tasks %}
            {% for task in tasks %}
            <div class="alert alert-success" role="alert">
                {{ task.description }}
                <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>%
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% endif %}
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });
        }
        $(function () {
            var timer = null;
            var xhr = null;
            $('.user_popup').hover(
                function(event) {
                    // mouse in event handler
                    var elem = $(event.currentTarget);
                    timer = setTimeout(function() {
                        timer = null;
                        xhr = $.ajax(
                            '/user/' + elem.first().text().trim() + '/popup').done(
                                function(data) {
                                    xhr = null;
                                    elem.popover({
                                        trigger: 'manual',
                                        html: true,
                                        animation: false,
                                        container: elem,
                                        content: data
                                    }).popover('show');
                                    flask_moment_render_all();
                                }
                            );
                    }, 1000);
                },
                function(event) {
                    // mouse out event handler
                    var elem = $(event.currentTarget);
                    if (timer) {
                        clearTimeout(timer);
                        timer = null;
                    }
                    else if (xhr) {
                        xhr.abort();
                        xhr = null;
                    }
                    else {
                        elem.popover('destroy');
                    }
                }
            );
        });
        function set_message_count(n) {
            $('#message_count').text(n);
            $('#message_count').css('visibility', n ? 'visible' : 'hidden');
        }
        function set_task_progress(task_id, progress) {
            $('#' + task_id + '-progress').text(progress);
        }
        {% if current_user.is_authenticated %}
        $(function() {
            var since = 0;
            setInterval(function() {
                $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
                    function(notifications) {
                        for (var i = 0; i < notifications.length; i++) {
                            switch (notifications[i].name) {
                                case 'unread_message_count':
                                    set_message_count(notifications[i].data);
                                    break;
                                case 'task_progress':
                                    set_task_progress(notifications[i].data.task_id,
                                        notifications[i].data.progress);
                                    break;
                            }
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 10000);
        });
        {% endif %}
    </script>
{% endblock %}

app/templates/dashboards/app1.html
{% extends "layout.html" %}

{% block title %} Dashboard 1 {% endblock title %}

<!--{% block stylesheets %}-->
<!--  {{ super() }}-->
<!--{% endblock stylesheets %}-->

{% block content %}

  <iframe
    noresize='noresize'
    style='position: absolute; background: transparent; width: 95%; height:100%;'
    src={{ dash_url }}
    frameborder="0">
  </iframe>

{% endblock content %}

<!--{% block javascripts %}-->
<!--  {{ super()}}-->
<!--{% endblock javascripts %}-->

app/templates/layout.html
<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Hydrologie</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Css link -->
		<style>
		  .upStuff{
			  display:none;
		  }
		</style>
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/icon.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
	    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/Leaflet.Coordinates-0.1.5.css')}}">
		<link rel="stylesheet" href="https://unpkg.com/leaflet-draw@1.0.2/dist/leaflet.draw.css" />
		<!-- Leaflet Drawing Plugin: https://github.com/codeofsumit/leaflet.pm -->

		<script type="text/javascript" src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
		<script type="text/javascript" src="https://unpkg.com/mathjs@5.4.2/dist/math.min.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/bundle.js') }}"></script>

		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/simple-statistics/1.0.0/simple_statistics.min.js"></script>
	</head>

	{% block head %}
	{% endblock %}

	<body id="top">



		<div class="wrapper">
			<!-- Sidebar  -->
			<nav id="sidebar">
				<div class="sidebar-header">
				</div>
				<button type="button" id="sidebarCollapse" class="btn" style="margin-left:0vh;margin-top:1vh;">
					<i id = "elementID" class="fas fa-align-left"></i>
				</button>
				<ul class="list-unstyled components">
					<li class="">
						<a href="/index" class="dropdown-toggle">
							<i class="fas fa-home fa-3x" style = ""></i>
							Accueil
						</a>
					</li>
					<li>
						<a href="#pageSubmenudata" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
							<i class="fas fa-database fa-3x"></i>
							Données
						</a>
						<ul class="collapse list-unstyled" id="pageSubmenudata">
							<li>
								<a href="{{ url_for('dashboards.app1_template') }}">Page 1</a>
							</li>
							<li>
								<a href="#">Page 2</a>
							</li>
							<li>
								<a href="#">Page 3</a>
							</li>
						</ul>
						<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
							<i class="fas fa-toolbox fa-3x"></i>
							Outils
						</a>
						<ul class="collapse list-unstyled" id="pageSubmenu">
							<li>
								<a href="/outils/decoupage_bassin">Découpage de bassins versants</a>
							</li>
							<li>
								<a href="#">Page 2</a>
							</li>
							<li>
								<a href="#">Page 3</a>
							</li>
						</ul>
						<a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
							<i class="fas fa-copy fa-3x"></i>
							Études
						</a>
						<ul class="collapse list-unstyled" id="pageSubmenu2">
							<li>
								<a href="/etudes/series_temporelles">Séries temporelles</a>
							</li>
							<li>
								<a href="#">Page 2</a>
							</li>
							<li>
								<a href="#">Page 3</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-question fa-3x"></i>
							FAQ
						</a>
					</li>
					<li>
						<a href="#">
							<i class="fas fa-paper-plane fa-3x"></i>
							Contact
						</a>
					</li>
				</ul>
			</nav>

			<div class="container" style="background-color:#f6f6f6">
				<div class="container" style="height: 4vh;background-color:#fff">
					{#
<!--					<h4 style="position: absolute; left: 10px; top: 10px">-->
<!--						{{ _('Hi, %(username)s!', username=current_user.username) }}-->
<!--					</h4>-->
					#}


				<nav class="collapse navbar-collapse navbar-right" role="navigation">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							{#
	<!--						<ul class="nav navbar-nav">-->
	<!--							<li><a href="{{ url_for('dashboards.app1_template') }}">{{ _('App1') }}</a></li>-->
	<!--							<li><a href="{{ url_for('dashboards.app2_template') }}">{{ _('App2') }}</a></li>-->
	<!--						</ul>-->
	<!--						{% if g.search_form %}-->
	<!--						<form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">-->
	<!--							<div class="form-group">-->
	<!--								{{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}-->
	<!--							</div>-->
	<!--						</form>-->
<!--							{% endif %}-->
							#}
							<ul class="nav navbar-nav navbar-right">
								{#
								<!--								{% if current_user.is_anonymous %}-->
<!--								<li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>-->
<!--								{% else %}-->
<!--								<li>-->
<!--									<a href="{{ url_for('main.messages') }}">{{ _('Messages') }}-->
<!--										{% set new_messages = current_user.new_messages() %}-->
<!--										<span id="message_count" class="badge"-->
<!--											  style="visibility: {% if new_messages %}visible-->
<!--																 {% else %}hidden{% endif %};">-->
<!--											{{ new_messages }}-->
<!--										</span>-->
<!--									</a>-->
<!--								</li>-->
<!--								<li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('Profile') }}</a></li>-->
<!--								<li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>-->
<!--								{% endif %}-->
								#}
							</ul>
						</div>
				</nav>
				</div>
				<!-- /main nav -->


						<!-- Page Content  -->
				<div id="content">
					<div>
						{% block content %}{% endblock %}
					</div>
				</div>
			</div>



		</div>


		<!-- load Js -->
		<script type=text/javascript>
          $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
		  <!-- Font Awesome JS -->

		<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
		<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
		<script type=text/javascript src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<!--		<script type="text/javascript" src="{{ url_for('static', filename='js/waypoints.min.js') }}"></script>-->
		<!--<script type="text/javascript" src="{{ url_for('static', filename='js/lightbox.js') }}"></script>-->
		<!--<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.counterup.min.js') }}"></script>-->
		<!--<script type="text/javascript" src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>-->
		<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.mixitup.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/wow.min.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.scrollUp.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.sticky.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.nav.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/leaflet-heat.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/choropleth.js') }}"></script>
		<!--<script type="text/javascript" src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.388.js"></script>-->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.2/leaflet.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/mtl-prel.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/Leaflet.CountrySelect.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/flow_acc.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/Leaflet.Coordinates-0.1.5.min.js') }}"></script>
		<script src="https://unpkg.com/esri-leaflet@2.2.3/dist/esri-leaflet.js"
		integrity="sha512-YZ6b5bXRVwipfqul5krehD9qlbJzc6KOGXYsDjU9HHXW2gK57xmWl2gU6nAegiErAqFXhygKIsWPKbjLPXVb2g=="
		crossorigin=""></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/2.1.0/leaflet.ajax.min.js"></script>
		<script src="https://unpkg.com/esri-leaflet/dist/esri-leaflet.js"></script>
		<script src="https://cdn.rawgit.com/mejackreed/Leaflet-IIIF/v2.0.1/leaflet-iiif.js"></script>
    	<script src="https://unpkg.com/leaflet-draw@1.0.2/dist/leaflet.draw.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/leaflet.browser.print.min.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/dom-to-image.min.js') }}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/togeojson.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/leaflet.filelayer.js') }}"></script>
		<script src="https://unpkg.com/shp-write@latest/shpwrite.js"></script>
		<script src='//api.tiles.mapbox.com/mapbox.js/plugins/leaflet-image/v0.0.4/leaflet-image.js'></script>

		<script type="text/javascript" src="{{ url_for('static', filename='js/maps.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>

		<script type="text/javascript">
			$body = $("body");

			$(document).on({
				ajaxStart: function() { $body.addClass("loading");    },
				 ajaxStop: function() { $body.removeClass("loading"); }
			});

		</script>
	</body>
</html>